version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: shekohex-octobot_server_1
      APP_PORT: 5001
      PROXY_AUTH_ADD: "true"
    container_name: shekohex-octobot_app_proxy_1

  server001:
    image: drakkarsoftware/octobot:2.0.9@sha256:f7dcbebf233af039c24cb10e9b92f31352b94ed991d64a17c0dffc204cedacbc
    restart: on-failure
    container_name: shekohex-octobot_server_1
    hostname: ${DEVICE_HOSTNAME}
    environment:
      - PUID=1000
      - PGID=1000
      - DEBUG=False
    volumes:
      - ${APP_DATA_DIR}/001/logs:/octobot/logs
      - ${APP_DATA_DIR}/001/user:/octobot/user
      - ${APP_DATA_DIR}/001/tentacles:/octobot/tentacles
      - ${APP_DATA_DIR}/001/backtesting:/octobot/backtesting
