version: "3.7"

services:
  application:
    image: ghcr.io/shekohex/lionzhd-app:nightly
    restart: on-failure
    container_name: shekohex-lionzhd_application_1
    hostname: ${DEVICE_HOSTNAME}
    environment:
      APP_NAME: Lionz
      APP_ENV: production
      APP_KEY: "${APP_KEY:-unset}"
      APP_DEBUG: false
      APP_URL: "http://${APP_DOMAIN}"
      LOG_CHANNEL: stack
      LOG_STACK: stdout,sentry
      LOG_LEVEL: debug
      DB_CONNECTION: sqlite
      DB_DATABASE: /data/database/database.sqlite
      SESSION_DRIVER: redis
      SESSION_LIFETIME: 120
      BROADCAST_CONNECTION: log
      QUEUE_CONNECTION: redis
      CACHE_STORE: redis
      REDIS_CLIENT: phpredis
      REDIS_HOST: redis
      REDIS_PASSWORD: null
      REDIS_PORT: 6379
      SCOUT_DRIVER: meilisearch
      SCOUT_QUEUE: true
      MEILISEARCH_HOST: http://meilisearch:7700
      MEILISEARCH_KEY: ${APP_PASSWORD}
      ARIA2_RPC_HOST: http://shekohex-aria2-ariang_server_1
      ARIA2_RPC_PORT: 6800
      ARIA2_RPC_SECRET: umbrel
      HTTP_CLIENT_USER_AGENT: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:133.0) Gecko/20100101 Firefox/133.0"
      XTREAM_CODES_API_HOST: http://lionzhd.com
      XTREAM_CODES_API_PORT: 8080
      XTREAM_CODES_API_USER: username
      XTREAM_CODES_API_PASS: password
      TELESCOPE_ENABLED: true
      SENTRY_LARAVEL_DSN: https://e8f00bae07ba46c2740da14a39f9ba84@o194072.ingest.us.sentry.io/4509104145563648
      SENTRY_TRACES_SAMPLE_RATE: 1.0
    ports:
      - 8000:80
    volumes:
      - ${APP_DATA_DIR}/data/database:/data/database
    depends_on:
      - queue
      - scheduler
      - redis

  queue:
    image: ghcr.io/shekohex/lionzhd-queue:nightly
    restart: on-failure
    container_name: shekohex-lionzhd_queue_1
    hostname: ${DEVICE_HOSTNAME}
    environment:
      APP_NAME: Lionz
      APP_ENV: production
      APP_KEY: "${APP_KEY:-unset}"
      APP_DEBUG: false
      APP_URL: "http://${APP_DOMAIN}"
      LOG_CHANNEL: stack
      LOG_STACK: stdout,sentry
      LOG_LEVEL: debug
      DB_CONNECTION: sqlite
      DB_DATABASE: /data/database/database.sqlite
      SESSION_DRIVER: redis
      SESSION_LIFETIME: 120
      BROADCAST_CONNECTION: log
      QUEUE_CONNECTION: redis
      CACHE_STORE: redis
      REDIS_CLIENT: phpredis
      REDIS_HOST: redis
      REDIS_PASSWORD: null
      REDIS_PORT: 6379
      SCOUT_DRIVER: meilisearch
      SCOUT_QUEUE: true
      MEILISEARCH_HOST: http://meilisearch:7700
      MEILISEARCH_KEY: ${APP_PASSWORD}
      ARIA2_RPC_HOST: http://shekohex-aria2-ariang_server_1
      ARIA2_RPC_PORT: 6800
      ARIA2_RPC_SECRET: umbrel
      HTTP_CLIENT_USER_AGENT: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:133.0) Gecko/20100101 Firefox/133.0"
      XTREAM_CODES_API_HOST: http://lionzhd.com
      XTREAM_CODES_API_PORT: 8080
      XTREAM_CODES_API_USER: username
      XTREAM_CODES_API_PASS: password
      TELESCOPE_ENABLED: true
      SENTRY_LARAVEL_DSN: https://e8f00bae07ba46c2740da14a39f9ba84@o194072.ingest.us.sentry.io/4509104145563648
      SENTRY_TRACES_SAMPLE_RATE: 1.0
    volumes:
      - ${APP_DATA_DIR}/data/database:/data/database
    depends_on:
      - redis
 
  scheduler:
    image: ghcr.io/shekohex/lionzhd-scheduler:nightly
    restart: on-failure
    container_name: shekohex-lionzhd_scheduler_1
    hostname: ${DEVICE_HOSTNAME}
    environment:
      APP_NAME: Lionz
      APP_ENV: production
      APP_KEY: "${APP_KEY:-unset}"
      APP_DEBUG: false
      APP_URL: "http://${APP_DOMAIN}"
      LOG_CHANNEL: stack
      LOG_STACK: stdout,sentry
      LOG_LEVEL: debug
      DB_CONNECTION: sqlite
      DB_DATABASE: /data/database/database.sqlite
      SESSION_DRIVER: redis
      SESSION_LIFETIME: 120
      BROADCAST_CONNECTION: log
      QUEUE_CONNECTION: redis
      CACHE_STORE: redis
      REDIS_CLIENT: phpredis
      REDIS_HOST: redis
      REDIS_PASSWORD: null
      REDIS_PORT: 6379
      SCOUT_DRIVER: meilisearch
      SCOUT_QUEUE: true
      MEILISEARCH_HOST: http://meilisearch:7700
      MEILISEARCH_KEY: ${APP_PASSWORD}
      ARIA2_RPC_HOST: http://shekohex-aria2-ariang_server_1
      ARIA2_RPC_PORT: 6800
      ARIA2_RPC_SECRET: umbrel
      HTTP_CLIENT_USER_AGENT: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:133.0) Gecko/20100101 Firefox/133.0"
      XTREAM_CODES_API_HOST: http://lionzhd.com
      XTREAM_CODES_API_PORT: 8080
      XTREAM_CODES_API_USER: username
      XTREAM_CODES_API_PASS: password
      TELESCOPE_ENABLED: true
      SENTRY_LARAVEL_DSN: https://e8f00bae07ba46c2740da14a39f9ba84@o194072.ingest.us.sentry.io/4509104145563648
      SENTRY_TRACES_SAMPLE_RATE: 1.0
    volumes:
      - ${APP_DATA_DIR}/data/database:/data/database
    depends_on:
      - redis

  meilisearch:
    image: getmeili/meilisearch:v1
    restart: on-failure
    container_name: shekohex-lionzhd_meilisearch_1
    hostname: ${DEVICE_HOSTNAME}
    environment:
      - PUID=1000
      - PGID=1000
      - MEILI_ENV=production
      - MEILI_NO_ANALYTICS=false
      - MEILI_SERVER_PROVIDER=docker
      - MEILI_MASTER_KEY=${APP_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/meilisearch:/meili_data

  redis:
    image: redis:alpine
    restart: on-failure
    container_name: shekohex-lionzhd_redis_1
    hostname: ${DEVICE_HOSTNAME}
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    volumes:
      - ${APP_DATA_DIR}/data/redis:/data
