version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: shekohex-lionzhd_server_1
      APP_PORT: 8000
      PROXY_AUTH_ADD: 'true'
    container_name: shekohex-lionzhd_app_proxy_1

  server:
    image: lionzhd:latest
    restart: on-failure
    container_name: shekohex-lionzhd_server_1
    hostname: ${DEVICE_HOSTNAME}
    environment:
      - PUID=1000
      - PGID=1000
      - MEILI_HTTP_URL=http://meilisearch:7700
      - MEILI_MASTER_KEY=${APP_PASSWORD}
      - ARIA2_RPC_HOST=shekohex-aria2-ariang_server_1
      - ARIA2_RPC_PORT=6800
      - DJANGO_SECRET_KEY=${APP_SEED}
      - DJANGO_ALLOWED_HOSTS=*
      - DEBUG=False

  meilisearch:
    image: getmeili/meilisearch:v1
    restart: on-failure
    container_name: shekohex-lionzhd_meilisearch_1
    hostname: ${DEVICE_HOSTNAME}
    ports:
      - 7700:7700
    environment:
      - PUID=1000
      - PGID=1000
      - MEILI_ENV=production
      - MEILI_NO_ANALYTICS=false
      - MEILI_SERVER_PROVIDER=docker
      - MEILI_MASTER_KEY=${APP_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/meilisearch:/meili_data
