version: "3.7"

services:
  ollama:
    image: ollama/ollama:0.5.7@sha256:7e672211886f8bd4448a98ed577e26c816b9e8b052112860564afaa2c105800e
    restart: on-failure
    container_name: shekohex-ollama_1
    hostname: ${DEVICE_HOSTNAME}
    mem_limit: 4gb
    mem_reservation: 4gb
    cpus: 2.0
    ports:
      - 11434:11434
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_KEEP_ALIVE=15m
      - OLLAMA_MAX_LOADED_MODELS=2
      - OLLAMA_LOAD_TIMEOUT=10m
    volumes:
      - ${APP_DATA_DIR}/data/:/root/.ollama
