version: "3.7"

services:
  glance_server:
    image: glanceapp/glance:v0.8.1@sha256:8993ed3e1e6830a0b84a3ca053572beaae394f2d93f1918bb931d1fc204dbbab
    restart: on-failure
    container_name: shekohex-glance_server_1
    hostname: ${DEVICE_HOSTNAME}
    stop_grace_period: 10s
    ports:
      - 8765:8080
    volumes:
      - ${APP_DATA_DIR}/data/config:/app/config
      - ${APP_DATA_DIR}/data/assets:/app/assets
