#!/usr/bin/env bash
set -euo pipefail

APP_DATA_DIR="$(readlink -f $(dirname "${BASH_SOURCE[0]}")/..)/data"

# Create the data directory if it doesn't exist
mkdir -p "${APP_DATA_DIR}"
# Create the sqlite database file if it doesn't exist
if [[ ! -f "${APP_DATA_DIR}/database/database.sqlite" ]]; then
	touch "${APP_DATA_DIR}/database/database.sqlite"
fi

LARAVEL_APP_KEY_FILE_PATH="${APP_DATA_DIR}/laravel-app-key.txt"


# We only generate and save the Laravel APP_KEY if it doesn't exist already
if [[ ! -f "${LARAVEL_APP_KEY_FILE_PATH}" ]]; then
	#  generates a laravel APP_KEY using the lionzhd-app container --> php artisan key:generate --show
	APP_KEY=$("${UMBREL_ROOT}/scripts/app" compose "${APP_ID}" run --rm app php artisan key:generate --show)
	# we remove the color codes and newlines from the output which cause laravel to fail to parse the APP_KEY
	echo "${APP_KEY}" | sed 's/\x1b\[[0-9;]*m//g' | tr -d '\r\n' > "${LARAVEL_APP_KEY_FILE_PATH}"
fi
